const botContract: any = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'ExecuteFailed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'llamaPay', type: 'address' },
      { indexed: false, internalType: 'address', name: 'from', type: 'address' },
      { indexed: false, internalType: 'address', name: 'to', type: 'address' },
      { indexed: false, internalType: 'uint216', name: 'amountPerSec', type: 'uint216' },
      { indexed: false, internalType: 'uint40', name: 'starts', type: 'uint40' },
      { indexed: false, internalType: 'uint40', name: 'frequency', type: 'uint40' },
      { indexed: false, internalType: 'bytes32', name: 'id', type: 'bytes32' },
    ],
    name: 'WithdrawCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'llamaPay', type: 'address' },
      { indexed: false, internalType: 'address', name: 'from', type: 'address' },
      { indexed: false, internalType: 'address', name: 'to', type: 'address' },
      { indexed: false, internalType: 'uint216', name: 'amountPerSec', type: 'uint216' },
      { indexed: false, internalType: 'uint40', name: 'starts', type: 'uint40' },
      { indexed: false, internalType: 'uint40', name: 'frequency', type: 'uint40' },
      { indexed: false, internalType: 'bytes32', name: 'id', type: 'bytes32' },
    ],
    name: 'WithdrawExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'llamaPay', type: 'address' },
      { indexed: false, internalType: 'address', name: 'from', type: 'address' },
      { indexed: false, internalType: 'address', name: 'to', type: 'address' },
      { indexed: false, internalType: 'uint216', name: 'amountPerSec', type: 'uint216' },
      { indexed: false, internalType: 'uint40', name: 'starts', type: 'uint40' },
      { indexed: false, internalType: 'uint40', name: 'frequency', type: 'uint40' },
      { indexed: false, internalType: 'bytes32', name: 'id', type: 'bytes32' },
    ],
    name: 'WithdrawScheduled',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'balances',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes[]', name: 'calls', type: 'bytes[]' },
      { internalType: 'bool', name: 'revertOnFail', type: 'bool' },
    ],
    name: 'batch',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'bot',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_llamaPay', type: 'address' },
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint216', name: '_amountPerSec', type: 'uint216' },
      { internalType: 'uint40', name: '_starts', type: 'uint40' },
      { internalType: 'uint40', name: '_frequency', type: 'uint40' },
    ],
    name: 'cancelWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newBot', type: 'address' }],
    name: 'changeBot',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'deposit', outputs: [], stateMutability: 'payable', type: 'function' },
  {
    inputs: [
      { internalType: 'bytes[]', name: '_calls', type: 'bytes[]' },
      { internalType: 'address', name: '_owner', type: 'address' },
    ],
    name: 'executeTransactions',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_llamaPay', type: 'address' },
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint216', name: '_amountPerSec', type: 'uint216' },
      { internalType: 'uint40', name: '_starts', type: 'uint40' },
      { internalType: 'uint40', name: '_frequency', type: 'uint40' },
    ],
    name: 'executeWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_llamaPay', type: 'address' },
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint216', name: '_amountPerSec', type: 'uint216' },
      { internalType: 'uint40', name: '_starts', type: 'uint40' },
      { internalType: 'uint40', name: '_frequency', type: 'uint40' },
    ],
    name: 'getWithdrawId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'llama',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'owners',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IERC20Permit', name: 'token', type: 'address' },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'permitToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'refund', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'address', name: '_llamaPay', type: 'address' },
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint216', name: '_amountPerSec', type: 'uint216' },
      { internalType: 'uint40', name: '_starts', type: 'uint40' },
      { internalType: 'uint40', name: '_frequency', type: 'uint40' },
    ],
    name: 'scheduleWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export default botContract;
